# Generated by Django 3.1.5 on 2021-02-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(default='detail blog', max_length=255),
        ),
    ]
